export const EXERCISE_LIBRARY = [
  // Legs
  { id:'barbell_back_squat',       name:'Barbell Back Squat',        group:'Legs'      },
  { id:'front_squat',              name:'Front Squat',               group:'Legs'      },
  { id:'goblet_squat',             name:'Goblet Squat',              group:'Legs'      },
  { id:'bulgarian_split_squat',    name:'Bulgarian Split Squat',     group:'Legs'      },
  { id:'walking_lunges',           name:'Walking Lunges',            group:'Legs'      },
  { id:'reverse_lunges',           name:'Reverse Lunges',            group:'Legs'      },
  { id:'step_ups',                 name:'Step-Ups',                  group:'Legs'      },
  { id:'leg_press',                name:'Leg Press',                 group:'Legs'      },
  { id:'hack_squat',               name:'Hack Squat',                group:'Legs'      },
  { id:'leg_extension',            name:'Leg Extension',             group:'Legs'      },
  { id:'romanian_deadlift',        name:'Romanian Deadlift',         group:'Legs'      },
  { id:'good_morning',             name:'Good Morning',              group:'Legs'      },
  { id:'glute_bridge',             name:'Glute Bridge',              group:'Legs'      },
  { id:'hip_thrust',               name:'Hip Thrust',                group:'Legs'      },
  { id:'cable_kickback',           name:'Cable Kickback',            group:'Legs'      },
  { id:'hamstring_curl',           name:'Hamstring Curl',            group:'Legs'      },
  { id:'nordic_curl',              name:'Nordic Curl',               group:'Legs'      },
  { id:'seated_calf_raise',        name:'Seated Calf Raise',         group:'Legs'      },
  { id:'standing_calf_raise',      name:'Standing Calf Raise',       group:'Legs'      },
  { id:'tibialis_raise',           name:'Tibialis Raise',            group:'Legs'      },
  { id:'box_jump',                 name:'Box Jump',                  group:'Legs'      },
  { id:'broad_jump',               name:'Broad Jump',                group:'Legs'      },
  { id:'jump_squat',               name:'Jump Squat',                group:'Legs'      },
  { id:'single_leg_rdl',           name:'Single-Leg Romanian Deadlift', group:'Legs'   },
  { id:'curtsy_lunge',             name:'Curtsy Lunge',              group:'Legs'      },
  { id:'wall_sit',                 name:'Wall Sit',                  group:'Legs'      },
  { id:'adductor_machine',         name:'Adductor Machine',          group:'Legs'      },
  { id:'clamshell',                name:'Clamshell',                 group:'Legs'      },
  { id:'monster_walk',             name:'Monster Walk',              group:'Legs'      },
  { id:'banded_lateral_walk',      name:'Banded Lateral Walk',       group:'Legs'      },
  { id:'hip_airplane',             name:'Hip Airplane',              group:'Legs'      },

  // Chest
  { id:'barbell_bench_press',      name:'Barbell Bench Press',       group:'Chest'     },
  { id:'dumbbell_bench_press',     name:'Dumbbell Bench Press',      group:'Chest'     },
  { id:'incline_bench_press',      name:'Incline Bench Press',       group:'Chest'     },
  { id:'incline_db_press',         name:'Incline Dumbbell Press',    group:'Chest'     },
  { id:'decline_bench_press',      name:'Decline Bench Press',       group:'Chest'     },
  { id:'push_up',                  name:'Push-Up',                   group:'Chest'     },
  { id:'weighted_push_up',         name:'Weighted Push-Up',          group:'Chest'     },
  { id:'deficit_push_up',          name:'Deficit Push-Up',           group:'Chest'     },
  { id:'chest_fly',                name:'Chest Fly',                 group:'Chest'     },
  { id:'cable_fly',                name:'Cable Fly',                 group:'Chest'     },
  { id:'pec_deck_fly',             name:'Pec Deck Fly',              group:'Chest'     },
  { id:'dips',                     name:'Dips',                      group:'Chest'     },
  { id:'machine_chest_press',      name:'Machine Chest Press',       group:'Chest'     },
  { id:'plyo_push_up',             name:'Plyo Push-Up',              group:'Chest'     },
  { id:'smith_machine_bench',      name:'Smith Machine Bench Press', group:'Chest'     },
  { id:'single_arm_db_press',      name:'Single-Arm Dumbbell Press', group:'Chest'     },

  // Back
  { id:'pull_up',                  name:'Pull-Up',                   group:'Back'      },
  { id:'chin_up',                  name:'Chin-Up',                   group:'Back'      },
  { id:'lat_pulldown',             name:'Lat Pulldown',              group:'Back'      },
  { id:'seated_cable_row',         name:'Seated Cable Row',          group:'Back'      },
  { id:'barbell_row',              name:'Barbell Row',               group:'Back'      },
  { id:'pendlay_row',              name:'Pendlay Row',               group:'Back'      },
  { id:'dumbbell_row',             name:'Dumbbell Row',              group:'Back'      },
  { id:'chest_supported_row',      name:'Chest-Supported Row',       group:'Back'      },
  { id:'t_bar_row',                name:'T-Bar Row',                 group:'Back'      },
  { id:'inverted_row',             name:'Inverted Row',              group:'Back'      },
  { id:'straight_arm_pulldown',    name:'Straight-Arm Pulldown',     group:'Back'      },
  { id:'single_arm_cable_row',     name:'Single-Arm Cable Row',      group:'Back'      },
  { id:'meadows_row',              name:'Meadows Row',               group:'Back'      },
  { id:'dumbbell_pullover',        name:'Dumbbell Pullover',         group:'Back'      },

  // Shoulders
  { id:'barbell_overhead_press',   name:'Barbell Overhead Press',    group:'Shoulders' },
  { id:'dumbbell_shoulder_press',  name:'Dumbbell Shoulder Press',   group:'Shoulders' },
  { id:'arnold_press',             name:'Arnold Press',              group:'Shoulders' },
  { id:'push_press',               name:'Push Press',                group:'Shoulders' },
  { id:'lateral_raise',            name:'Lateral Raise',             group:'Shoulders' },
  { id:'front_raise',              name:'Front Raise',               group:'Shoulders' },
  { id:'rear_delt_raise',          name:'Rear Delt Raise',           group:'Shoulders' },
  { id:'upright_row',              name:'Upright Row',               group:'Shoulders' },
  { id:'cuban_press',              name:'Cuban Press',               group:'Shoulders' },
  { id:'y_raise',                  name:'Y Raise',                   group:'Shoulders' },
  { id:'handstand_push_up',        name:'Handstand Push-Up',         group:'Shoulders' },
  { id:'pike_push_up',             name:'Pike Push-Up',              group:'Shoulders' },
  { id:'cable_lateral_raise',      name:'Cable Lateral Raise',       group:'Shoulders' },
  { id:'machine_shoulder_press',   name:'Machine Shoulder Press',    group:'Shoulders' },
  { id:'band_pull_apart',          name:'Band Pull-Apart',           group:'Shoulders' },
  { id:'face_pull',                name:'Face Pull',                 group:'Shoulders' },
  { id:'rear_delt_fly',            name:'Rear Delt Fly',             group:'Shoulders' },
  { id:'shrugs',                   name:'Shrugs',                    group:'Shoulders' },
  { id:'landmine_press',           name:'Landmine Press',            group:'Shoulders' },
  { id:'scap_push_up',             name:'Scap Push-Up',              group:'Shoulders' },

  // Biceps
  { id:'ez_bar_curl',              name:'EZ Bar Curl',               group:'Biceps'    },
  { id:'barbell_curl',             name:'Barbell Curl',              group:'Biceps'    },
  { id:'dumbbell_curl',            name:'Dumbbell Curl',             group:'Biceps'    },
  { id:'hammer_curl',              name:'Hammer Curl',               group:'Biceps'    },
  { id:'incline_db_curl',          name:'Incline Dumbbell Curl',     group:'Biceps'    },
  { id:'concentration_curl',       name:'Concentration Curl',        group:'Biceps'    },
  { id:'preacher_curl',            name:'Preacher Curl',             group:'Biceps'    },
  { id:'cable_curl',               name:'Cable Curl',                group:'Biceps'    },
  { id:'spider_curl',              name:'Spider Curl',               group:'Biceps'    },
  { id:'chin_up_hold',             name:'Chin-Up Hold',              group:'Biceps'    },
  { id:'wrist_curl',               name:'Wrist Curl',                group:'Biceps'    },
  { id:'reverse_wrist_curl',       name:'Reverse Wrist Curl',        group:'Biceps'    },

  // Triceps
  { id:'skullcrusher',             name:'Skullcrusher',              group:'Triceps'   },
  { id:'rope_pushdown',            name:'Rope Pushdown',             group:'Triceps'   },
  { id:'overhead_tricep_ext',      name:'Overhead Tricep Extension', group:'Triceps'   },
  { id:'dumbbell_kickback',        name:'Dumbbell Kickback',         group:'Triceps'   },
  { id:'jm_press',                 name:'JM Press',                  group:'Triceps'   },
  { id:'diamond_push_up',          name:'Diamond Push-Up',           group:'Triceps'   },
  { id:'bench_dips',               name:'Bench Dips',                group:'Triceps'   },
  { id:'close_grip_push_up',       name:'Close-Grip Push-Up',        group:'Triceps'   },
  { id:'single_arm_pushdown',      name:'Single-Arm Pushdown',       group:'Triceps'   },
  { id:'tate_press',               name:'Tate Press',                group:'Triceps'   },
  { id:'close_grip_bench',         name:'Close-Grip Bench Press',    group:'Triceps'   },

  // Core
  { id:'plank',                    name:'Plank',                     group:'Core'      },
  { id:'side_plank',               name:'Side Plank',                group:'Core'      },
  { id:'dead_bug',                 name:'Dead Bug',                  group:'Core'      },
  { id:'bird_dog',                 name:'Bird Dog',                  group:'Core'      },
  { id:'hollow_hold',              name:'Hollow Hold',               group:'Core'      },
  { id:'hanging_leg_raise',        name:'Hanging Leg Raise',         group:'Core'      },
  { id:'toes_to_bar',              name:'Toes-to-Bar',               group:'Core'      },
  { id:'cable_crunch',             name:'Cable Crunch',              group:'Core'      },
  { id:'russian_twist',            name:'Russian Twist',             group:'Core'      },
  { id:'bicycle_crunch',           name:'Bicycle Crunch',            group:'Core'      },
  { id:'reverse_crunch',           name:'Reverse Crunch',            group:'Core'      },
  { id:'ab_wheel_rollout',         name:'Ab Wheel Rollout',          group:'Core'      },
  { id:'pallof_press',             name:'Pallof Press',              group:'Core'      },
  { id:'mountain_climbers',        name:'Mountain Climbers',         group:'Core'      },
  { id:'v_up',                     name:'V-Up',                      group:'Core'      },
  { id:'push_up_shoulder_tap',     name:'Push-Up to Shoulder Tap',   group:'Core'      },
  { id:'suitcase_carry',           name:'Suitcase Carry',            group:'Core'      },
  { id:'renegade_row',             name:'Renegade Row',              group:'Core'      },
  { id:'reverse_hyperextension',   name:'Reverse Hyperextension',    group:'Core'      },
  { id:'back_extension',           name:'Back Extension',            group:'Core'      },
  { id:'copenhagen_plank',         name:'Copenhagen Plank',          group:'Core'      },
  { id:'jefferson_curl',           name:'Jefferson Curl',            group:'Core'      },

  // Full Body
  { id:'conventional_deadlift',    name:'Conventional Deadlift',     group:'Full Body' },
  { id:'sumo_deadlift',            name:'Sumo Deadlift',             group:'Full Body' },
  { id:'trap_bar_deadlift',        name:'Trap Bar Deadlift',         group:'Full Body' },
  { id:'kettlebell_swing',         name:'Kettlebell Swing',          group:'Full Body' },
  { id:'rack_pull',                name:'Rack Pull',                 group:'Full Body' },
  { id:'farmer_carry',             name:'Farmer Carry',              group:'Full Body' },
  { id:'turkish_get_up',           name:'Turkish Get-Up',            group:'Full Body' },
  { id:'burpees',                  name:'Burpees',                   group:'Full Body' },
  { id:'bear_crawl',               name:'Bear Crawl',                group:'Full Body' },
  { id:'crab_walk',                name:'Crab Walk',                 group:'Full Body' },
  { id:'medicine_ball_slam',       name:'Medicine Ball Slam',        group:'Full Body' },
  { id:'wall_ball',                name:'Wall Ball',                 group:'Full Body' },
  { id:'sandbag_carry',            name:'Sandbag Carry',             group:'Full Body' },
  { id:'thruster',                 name:'Thruster',                  group:'Full Body' },
  { id:'clean_and_press',          name:'Clean and Press',           group:'Full Body' },
  { id:'power_clean',              name:'Power Clean',               group:'Full Body' },
  { id:'snatch',                   name:'Snatch',                    group:'Full Body' },
  { id:'high_pull',                name:'High Pull',                 group:'Full Body' },

  // Cardio
  { id:'battle_ropes',             name:'Battle Ropes',              group:'Cardio'    },
  { id:'sled_push',                name:'Sled Push',                 group:'Cardio'    },
  { id:'sled_pull',                name:'Sled Pull',                 group:'Cardio'    },
  { id:'rowing_machine_sprint',    name:'Rowing Machine Sprint',     group:'Cardio'    },
  { id:'assault_bike_sprint',      name:'Assault Bike Sprint',       group:'Cardio'    },
  { id:'jump_rope',                name:'Jump Rope',                 group:'Cardio'    },
]

export const EXERCISE_GROUPS = ['All','Legs','Chest','Back','Shoulders','Biceps','Triceps','Core','Full Body','Cardio']
